repository:
  name: probot-settings-1
  description: Repository, Pull Requests for GitHub repository settings
  homepage: https://github.com/apps/settings
  topics: probot-app, github-app, probot-settings
  has_wiki: false
